# @package _global_
env:
  name: pz-mpe-penalty-spread-v1
  max_ep_length: 25

  wrappers:
    - RecordEpisodeStatistics
    - SquashDones

algorithm:
  num_env_steps: 10000000
  log_interval: 100000
  save_interval: 1000000
  eval_interval: 250000
