# @package _global_
env:
  name: rware-imgdict-tiny-2ag-v1
  arguments:
    sensor_range: 2
    layout:
      - |
        ....................
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        ....................
        .........gg.........
      - |
        ....................
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        ....................
        .........gg.........
      - |
        ....................
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        ....................
        .........gg.........
      - |
        ....................
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        ....................
        .........gg.........
      - |
        ....................
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        ....................
        .........gg.........
      - |
        ....................
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        ....................
        .........gg.........
      - |
        ....................
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        ....................
        .........gg.........
      - |
        ....................
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        .xx..............xx.
        ....................
        .........gg.........

  wrappers:
    - RecordEpisodeStatistics
    - SquashDones
    - ConcatDictObservation

algorithm:
  num_env_steps: 50000000
  log_interval: 250000
  save_interval: null
  eval_interval: 1000000
